---
- hosts: localhost
  tasks:
    - debug:

    - amazon.aws.ec2_instance:
        name: node1-xt4s7
        key_name: ssh_provision_xt4s7
        vpc_subnet_id: subnet-07141c97c5d0ac3ca
        instance_type: t3.medium
        security_group: ocp4-cluster-xt4s7-BastionSG-LEQPX8IUO2B4
        network:
          assign_public_ip: true
        image_id: ami-02e52ff31455af070
        tags:
          Environment: Testing

    - amazon.aws.ec2_instance_info:
      register: output

    - debug: var=output
