---
- hosts: localhost
  tasks:
    - debug:

    - amazon.aws.ec2_instance:
        region: us-east-2
        name: "{{ item }}-xt4s7"
        key_name: ssh_provision_xt4s7
        vpc_subnet_id: subnet-07141c97c5d0ac3ca
        instance_type: t3.medium
        security_group: ocp4-cluster-xt4s7-BastionSG-LEQPX8IUO2B4
        network:
          assign_public_ip: true
        image_id: ami-02e52ff31455af070
        volumes:
        - device_name: /dev/sda1
          ebs:
            volume_size: 50
            delete_on_termination: true
        tags:
          AnsibleGroup: demo_nodes
          Environment: demo
          NodeName: "{{ item }}"
      loop:
        - node1
        - node2
        - node3
        - node4

    - amazon.aws.ec2_instance_info:
        region: us-east-2
      register: output

    - debug: var=output
